global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fcm_server'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'batch_server'
    static_configs:
      - targets: ['host.docker.internal:3002']

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
